- name: Get Settings
  uri:
    url: "{{ domain.url }}/api/settings"
    method: GET
    return_content: true
    validate_certs: no
    headers:
      Authorization: "Bearer {{ token }}"
  register: portainer_settings

- name: Set Settings
  uri:
    url: "{{ domain.url }}/api/settings"
    method: PUT
    return_content: true
    validate_certs: no
    body_format: json
    headers:
      Authorization: "Bearer {{ token }}"
    body: "{{ configuration.settings | to_json }}"