
- name: "Create user '{{ user_in_docker.name }}'"
  include_tasks: create_users/create_users.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  when:
    - user.username == user_in_docker.name
    - user_in_docker.docker_services is defined
    - "'portainer' in user_in_docker.docker_services"
# return: token variable